---
- name: Include Distro Specific Vars
  include_vars: "RedHat7.yml"

- name: Create Aerospike download directory.
  file:
    path: "{{ aerospike_source_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Aerospike log directory.
  file:
    path: "{{ aerospike_log_directory }}"
    state: directory

## Aerospike site does not have SSL
- name: Download Aerospike package.
  unarchive:
    src: "{{ aerospike_download_url }}"
    dest: "{{ aerospike_source_directory }}"
    remote_src: True
    validate_certs: no

- name: install aerospike.
  shell: 'cd {{ aerospike_source_directory }}/{{ aerospike_package_name }}; ./asinstall; exit 0'

- name: Place Aerospike configuration file.
  template:
    src: aerospike.conf.j2
    dest: "{{ aerospike_config_destination }}"
    owner: root
    group: root
    force: yes
  notify:
    - start aerospike
